permisos_usuarios = {
    'AD': [
        'cambiar_password',
        'cambiar_estado_usuarios',
        'cambiar_estado_jornada',
        'cambiar_estado_solicitudes',
        'change_permission',
        'add_user',
        'change_user',
        'view_user',
        'add_zona',
        'change_zona',
        'view_zona',
        'add_perfil',
        'change_perfil',
        'view_perfil',
        'add_beneficiado',
        'change_beneficiado',
        'view_beneficiado',
        'add_producto',
        'change_producto',
        'view_producto',
        'add_tipoinsumo',
        'change_tipoinsumo',
        'view_tipoinsumo',
        'add_laboratorio',
        'change_laboratorio',
        'view_laboratorio',
        'add_almacen',
        'change_almacen',
        'view_almacen',
        'add_inventario',
        'change_inventario',
        'view_inventario',
        'add_detalleingreso',
        'change_detalleingreso',
        'view_detalleingreso',
        'add_ingreso',
        'change_ingreso',
        'view_ingreso',
        'add_jornada',
        'change_jornada',
        'view_jornada',
        'add_tipomov',
        'change_tipomov',
        'view_tipomov',
        'add_detallejornada',
        'change_detallejornada',
        'view_detallejornada',
        'add_historial',
        'change_historial',
        'view_historial',
        'add_detallesolicitud',
        'change_detallesolicitud',
        'view_detallesolicitud',
        'add_solicitud',
        'change_solicitud',
        'view_solicitud'

    ],
    'AL': [
        'cambiar_estado_jornada',
        'cambiar_estado_solicitudes',
        ],
    'AT': [
        'cambiar_password',
        'cambiar_estado_jornada',
        'cambiar_estado_solicitudes',
    ],
    'JC': [
        'add_solicitud',
    ],
    'PA': [
        'add_solicitud',
    ]
}