# Generated by Django 4.2.10 on 2024-03-19 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona_residencia', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacionalidad', models.CharField(choices=[('V-', 'V-'), ('E-', 'E-'), ('J-', 'J-')], default='V-', max_length=2)),
                ('cedula', models.CharField(max_length=8)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=11)),
                ('genero', models.CharField(choices=[('MA', 'Masculino'), ('FE', 'Femenino')], max_length=2)),
                ('f_nacimiento', models.DateField()),
                ('embarazada', models.BooleanField()),
                ('c_residencia', models.FileField(blank=True, null=True, upload_to='constancias_residencias/')),
                ('direccion', models.TextField()),
                ('rol', models.CharField(choices=[('AD', 'Administrador'), ('AL', 'Almacenista'), ('AT', 'Atención al Cliente'), ('JC', 'Jefe de Comunidad'), ('PA', 'Paciente')], default='PA', max_length=2)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entidades.zona')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
                'permissions': [('cambiar_password', 'cambiar contraseña a usuarios'), ('cambiar_estado_usuarios', 'cambiar estado de usuarios'), ('cambiar_estado_jornada', 'cambiar estatus de jornadas'), ('cambiar_estado_solicitudes', 'cambiar status de solicitudes')],
            },
        ),
        migrations.CreateModel(
            name='Beneficiado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacionalidad', models.CharField(choices=[('V-', 'V-'), ('E-', 'E-'), ('J-', 'J-')], default='V-', max_length=2)),
                ('cedula', models.CharField(max_length=8)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=11)),
                ('genero', models.CharField(choices=[('MA', 'Masculino'), ('FE', 'Femenino')], max_length=2)),
                ('f_nacimiento', models.DateField()),
                ('embarazada', models.BooleanField()),
                ('c_residencia', models.FileField(blank=True, null=True, upload_to='constancias_residencias/')),
                ('direccion', models.TextField()),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiados', to='entidades.perfil')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entidades.zona')),
            ],
            options={
                'verbose_name': 'Beneficiado',
                'verbose_name_plural': 'Beneficiados',
            },
        ),
    ]
