# Generated by Django 4.0.2 on 2024-03-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_alter_beneficiado_c_residencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiado',
            name='nacionalidad',
            field=models.CharField(choices=[('V-', 'Venezolano'), ('FE', 'Extranjero')], default='V-', max_length=2),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nacionalidad',
            field=models.CharField(choices=[('V-', 'Venezolano'), ('FE', 'Extranjero')], default='V-', max_length=2),
        ),
    ]
