# Generated by Django 4.2.10 on 2024-03-16 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("entidades", "0003_alter_beneficiado_nacionalidad_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficiado",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="beneficiados",
                to="entidades.perfil",
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfil",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
