# Generated by Django 4.2.10 on 2024-03-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_alter_beneficiado_nacionalidad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'permissions': [('cambiar_password', 'cambiar contraseña a usuarios'), ('cambiar_estado_usuarios', 'cambiar estado de usuarios'), ('cambiar_estado_jornada', 'cambiar estatus de jornadas'), ('cambiar_estado_solicitudes', 'cambiar status de solicitudes')], 'verbose_name': 'perfil', 'verbose_name_plural': 'perfiles'},
        ),
    ]
