# Generated by Django 4.2.10 on 2024-03-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entidades", "0004_alter_beneficiado_perfil_alter_perfil_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficiado",
            name="nacionalidad",
            field=models.CharField(
                choices=[("V-", "V-"), ("E-", "E-"), ("J-", "J-")],
                default="V-",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="nacionalidad",
            field=models.CharField(
                choices=[("V-", "V-"), ("E-", "E-"), ("J-", "J-")],
                default="V-",
                max_length=2,
            ),
        ),
    ]
