# Generated by Django 4.2.10 on 2024-03-16 21:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entidades", "0004_alter_perfil_options"),
        ("entidades", "0005_alter_beneficiado_nacionalidad_and_more"),
    ]

    operations = []
