# Generated by Django 4.2.10 on 2024-03-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_producto_if_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='if_expire_date',
            field=models.BooleanField(blank=True, null=True, verbose_name='Si caduca'),
        ),
    ]
