# Generated by Django 4.2.10 on 2024-03-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_producto_if_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='if_expire_date',
            field=models.CharField(choices=[('SI', 'SÍ'), ('NO', 'NO')], default='SI', max_length=2, verbose_name='Si caduca'),
            preserve_default=False,
        ),
    ]
