# Generated by Django 4.2.10 on 2024-03-18 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("entidades", "0001_initial"),
        ("movimientos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitud",
            name="perfil",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="entidades.perfil",
            ),
        ),
    ]
