# Generated by Django 4.2.10 on 2024-03-18 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("entidades", "0001_initial"),
        ("movimientos", "0002_solicitud_perfil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitud",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="entidades.perfil"
            ),
        ),
    ]
