# Generated by Django 4.2.10 on 2024-03-16 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0002_alter_inventario_producto"),
        ("movimientos", "0004_alter_historial_producto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historial",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="historial",
                to="inventario.inventario",
            ),
        ),
    ]
