# Generated by Django 4.2.10 on 2024-03-16 03:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movimientos", "0005_alter_historial_producto"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historial",
            options={
                "ordering": ["-id"],
                "verbose_name": "Movimiento de Inventario",
                "verbose_name_plural": "Movimientos de Inventario",
            },
        ),
    ]
