# Generated by Django 4.2.10 on 2024-03-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movimientos", "0007_alter_historial_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historial",
            name="fecha_mov",
            field=models.DateField(auto_now_add=True),
        ),
    ]
