# Generated by Django 4.2.10 on 2024-03-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movimientos", "0008_alter_historial_fecha_mov"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detallesolicitud",
            name="cant_entregada",
            field=models.IntegerField(default=0),
        ),
    ]
